// Band action types
export const BANDS_LOADING = "BAND_LOADING";
export const BANDS_SUCCESSFULL = "BAND_SUCCESSFULL";
export const BANDS_FAILED = "BAND_FAILED";
export const BAND_SELECTED = "BAND_SELECTED";

export const FAV_BAND_STARTED = "FAV_BAND_STARTED";
export const FAV_BAND_SUBMITTED = "FAV_BAND_SUBMITTED";
export const FAV_BAND_FAILED = "FAV_BAND_FAILED";

// Concert action types
export const CONCERTS_LOADING = "CONCERTS_LOADING";
export const CONCERTS_SUCCESSFULL = "CONCERTS_SUCCESSFULL";
export const CONCERTS_FAILED = "CONCERTS_FAILED";
